btl/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import url
from customers import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customers/', include('customers.urls')),
    path('produce/', include('produces.urls')),
    path('warehouse/', include('warehouse.urls')),
    path('',views.user_login, name="login" ),
    path('register/',views.register, name="register" ),
    path('home/', views.home, name="home")
]


urlpatterns += [url(r'^i18n/', include('django.conf.urls.i18n')),]
urlpatterns += i18n_patterns(url(r'^admin/', admin.site.urls))

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('add-cart-clothes/<int:id>/', views.add_cart_clothes, name="add_cart_clothes"),
    path('view-cart/', views.view_cart, name="view_cart"),
    path('delete-cart-clothes/<int:id>/', views.delete_cart_clothes, name="delete_cart_clothes"),
    path('get-receiver/', views.get_receiver, name="get_receiver"),
    path('get-payment-method/', views.payment, name="payment"),
    path('order/', views.order, name="order"),
]

customers/models.py
from warehouse.models import Electro
from produces.models import ItemBook, ItemClothes, ItemElectro
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
USER_PROFILE_GENDER_CHOICES = [
        (0, 'Khác'),
        (1, 'Nam'),
        (2, 'Nữ'),
    ]
class Customer(models.Model):
    class Meta:
        db_table = "customer"
        verbose_name = 'Customer'
        verbose_name_plural = 'Customer'
    uid = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    birthday = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=255)
    gender = models.PositiveSmallIntegerField( choices=USER_PROFILE_GENDER_CHOICES, default=0)
    id_selfie = models.ImageField(('Selfie'),upload_to="media/profile",default = 'media/profile/1.jpg')

    class Meta:
        db_table = "customer"
        verbose_name = 'Customer'
        verbose_name_plural = 'Customer'
        
class CommentClothes(models.Model):
    reviewer = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE
    )
    item = models.ForeignKey(
        ItemClothes,
        on_delete=models.CASCADE
    )
    content = models.TextField()
    review = models.IntegerField(default=0)
    
    class Meta:
        db_table = "comment_clothes"
        verbose_name = 'Đánh giá về quần áo'
        verbose_name_plural = 'Đánh giá về quần áo'
    
class CommentElectro(models.Model):
    reviewer = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE
    )
    item = models.ForeignKey(
        ItemElectro,
        on_delete=models.CASCADE
    )
    content = models.TextField()
    review = models.IntegerField(default=0)
    
    class Meta:
        db_table = "comment_electro"
        verbose_name = 'Đánh giá về đồ điện tử'
        verbose_name_plural = 'Đánh giá về đồ điện tử'
    
class CommentBook(models.Model):
    reviewer = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE
    )
    item = models.ForeignKey(
        ItemBook,
        on_delete=models.CASCADE
    )
    content = models.TextField()
    review = models.IntegerField(default=0)
    
    class Meta:
        db_table = "comment_book"
        verbose_name = 'Đánh giá về sách'
        verbose_name_plural = 'Đánh giá về sách'
   
class LikeClothes(models.Model):
    item = models.ForeignKey(
        ItemClothes,
        on_delete=models.CASCADE
    )
    like = models.BigIntegerField()
    
    class Meta:
        db_table = "like_clothes"
        verbose_name = 'Yêu thích quần áo'
        verbose_name_plural = 'Yêu thích quần áo'

class LikeElectro(models.Model):
    item = models.ForeignKey(
        ItemElectro,
        on_delete=models.CASCADE
    )
    like = models.BigIntegerField()
    
    class Meta:
        db_table = "like_electro"
        verbose_name = 'Yêu thích đồ điện tử'
        verbose_name_plural = 'Yêu thích đồ điện tử'
        
class LikeBook(models.Model):
    item = models.ForeignKey(
        ItemBook,
        on_delete=models.CASCADE
    )
    like = models.BigIntegerField()
    
    class Meta:
        db_table = "like_book"
        verbose_name = 'Yêu thích sách'
        verbose_name_plural = 'Yêu thích sách'
        
class Cart(models.Model):
    customer = models.OneToOneField(
        Customer,
        on_delete=models.CASCADE
    )
    nameCart = models.CharField(max_length=255,null=True, blank=True)
    
    class Meta:
        db_table = "cart"
        verbose_name = 'Giỏ hàng'
        verbose_name_plural = 'Giỏ hàng'
        
    def __str__(self):
        return str(self.customer)+"_"+ str(self.id)
    

class CartClothes(models.Model):
    item = models.ForeignKey(
        ItemClothes,
        on_delete=models.CASCADE,
        null=True, blank=True
    )
    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE,
        null=True, blank=True
    )
    amount =  models.IntegerField(default=0)
    total = models.BigIntegerField(null=True, blank=True)
    
    class Meta:
        db_table = "clothes_cart"
        verbose_name = 'Giỏ hàng quần áo'
        verbose_name_plural = 'Giỏ hàng quần áo'
    
    
class CartElectro(models.Model):
    item = models.ForeignKey(
        ItemElectro,
        on_delete=models.CASCADE,
        null=True, blank=True
    )
    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE,
        null=True, blank=True
    )
    amount =  models.IntegerField(default=0)
    total = models.BigIntegerField(null=True, blank=True)
    
    class Meta:
        db_table = "cart_electro"
        verbose_name = 'Giỏ hàng điện tử'
        verbose_name_plural = 'Giỏ hàng điện tử'
    
class CartBook(models.Model):
    item = models.ForeignKey(
        ItemBook,
        on_delete=models.CASCADE,
        null=True, blank=True
    )
    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE,
        null=True, blank=True
    )
    amount =  models.IntegerField(default=0)
    total = models.BigIntegerField(null=True, blank=True)
    class Meta:
        db_table = "cart_book"
        verbose_name = 'Giỏ hàng sách'
        verbose_name_plural = 'giỏ hàng sách'
    

class Receiver(models.Model):
    customer = models.OneToOneField(
        Customer,
        on_delete=models.CASCADE,
        null=True, blank=True
    )
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    house_number = models.CharField(max_length=255)
    commune = models.CharField(max_length=255)
    district = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    note = models.TextField(null=True, blank=True)
    
    class Meta:
        db_table = "receiver"
        verbose_name = 'Người nhận'
        verbose_name_plural = 'Người nhận'
    
class Shipment(models.Model):
    commune = models.CharField(max_length=255)
    district = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    fee = models.BigIntegerField(null=True, blank=True)
    
    class Meta:
        db_table = "shipment"
        verbose_name = 'Vận chuyển'
        verbose_name_plural = 'Vận chuyển'
        
    def __str__(self):
        return str(self.fee) +"đ"
        
class Order(models.Model):
    customer = models.ForeignKey(
        Receiver,
        on_delete=models.CASCADE
    )
    total = models.BigIntegerField(null=True, blank=True)
    product = models.TextField(null=True, blank=True)
    ship = models.ForeignKey(
        Shipment,
        on_delete=models.CASCADE
    )
    into_money = models.BigIntegerField(null=True, blank=True)
    payment_methods = models.CharField(max_length=255)
    
    class Meta:
        db_table = "order"
        verbose_name = 'Đặt hàng'
        verbose_name_plural = 'Đặt hàng'
    
PAYMENT_METHOD =[
    (0, 'Thanh toán khi nhận hàng'),
    (1, 'Thanh toán qua thẻ ngân hàng'),
    (0, 'Thanh toán qua ví momo ')
]

class Payment(models.Model):
    user = models.OneToOneField(
        Customer,
        on_delete=models.CASCADE,
        null=True, blank=True
    )
    method = models.PositiveSmallIntegerField( choices=PAYMENT_METHOD, default=0)

    class Meta:
        db_table = "payment"
        verbose_name = 'Thanh toán'
        verbose_name_plural = 'Thanh toán'
    
    

customers/forms.py
from django import forms
from django.contrib.auth.forms import User
from .models import *

PAYMENT_METHOD =[
    (0, 'Thanh toán khi nhận hàng'),
    (1, 'Thanh toán qua thẻ ngân hàng'),
    (2, 'Thanh toán qua ví momo ')
]

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(), max_length=255)
    password = forms.CharField(widget=forms.PasswordInput(), max_length=255)
    
    
class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    password_repeat = forms.CharField(widget=forms.PasswordInput())
    name = forms.CharField(widget=forms.TextInput())
    email = forms.EmailField(widget=forms.EmailInput())
    phone = forms.CharField(widget=forms.NumberInput())
   
class ReceiverForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput())
    phone = forms.CharField(widget=forms.TextInput())
    house_number = forms.CharField(widget=forms.TextInput())
    commune = forms.CharField(widget=forms.TextInput())
    district = forms.CharField(widget=forms.TextInput())
    city = forms.CharField(widget=forms.TextInput())
    note = forms.CharField(widget=forms.Textarea(), required=False)
    
class PaymentMethodForm(forms.Form):
    method =  forms.ChoiceField(choices = PAYMENT_METHOD)
    
class OrderForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput())
    phone = forms.CharField(widget=forms.TextInput())
    house_number = forms.CharField(widget=forms.TextInput())
    commune = forms.CharField(widget=forms.TextInput())
    district = forms.CharField(widget=forms.TextInput())
    city = forms.CharField(widget=forms.TextInput())
    note = forms.CharField(widget=forms.Textarea())
    total = forms.IntegerField(widget=forms.NumberInput())
    fee_ship = forms.IntegerField(widget=forms.NumberInput())
    into_money = forms.IntegerField(widget=forms.NumberInput())
    method = forms.CharField(widget=forms.TextInput())

customers/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>User</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <!-- Google fonts-->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&amp;display=swap"
        rel="stylesheet" />
    <link
        href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&amp;display=swap"
        rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&amp;display=swap"
        rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>

<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm" id="mainNav">
        <div class="container px-5 d-flex">
            <a class="navbar-brand fw-bold" href="#page-top"> <img src="../static/assets/images/Lymn_logo.png" alt=""></a>

            <a class="nav-toggler d-block d-md-none text-dark" data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation" href="javascript:void(0)"><i class="bi-list bi-close"></i></a>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-lg-0">
                    <li class="nav-item"><a class="nav-link me-lg-3" href="trangchu.html">TRANG CHỦ</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="quanao.html">QUẦN ÁO</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="phukien.html">ĐIỆN TỬ</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="phukien.html">SÁCH</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="blog.html">BLOG</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="lienhe.html">LIÊN HỆ</a></li>
                    <li class="nav-item"><a class="nav-link" href="gioithieu.html">GIỚI THIỆU</a></li>
                </ul>

            </div>
        </div>
    </nav>
    <!-- Mashead header-->
    <header class="masthead">
        <div class="container px-5">
            <div class="row m-0 ">
                <div class="col-6 d-flex " >
                    <span>Danh sách yêu thích (0) |</span>
                    <input class="form-input" type="search" placeholder="Tìm kiếm" aria-label="Tìm kiếm" />
                    <i class="bi-search"></i>
                </div>
                <div class="pb-4 col-6 content-header dropdown" style="padding-right: 0; text-align: right; width:51%">

                    <a href="giohang.html"><span >Giỏ hàng (0)</span></a> | <i class="bi-person-fill" aria-hidden="true"></i><span class="dropdown-toggle" data-bs-toggle="dropdown"> Tài khoản </i></span></span>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="Userdd">
                        <a class="dropdown-item" href="{%url 'register' %}"><i
                                class="bi bi-box-arrow-in-right m-r-5 m-l-5"></i> Đăng ký</a>

                        <a class="dropdown-item" href="{% url 'login' %}"><i
                                class="bi bi-box-arrow-in-right m-r-5 m-l-5"></i> Đăng nhập</a>
                    </div>
                </div>

            </div>
            <div class="row m-0 bg-light">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item text-dark"><a class="home" href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item text-dark">Đăng nhập</li>
                </ul>
            </div>
        </div>
    </header>
    
    <section class=" d-flex justify-content-center mb-4" style="margin-top:5%">
        <form class="form-login" method="POST" action="{% url 'login' %}">
            {% csrf_token %}
            <p class="h4 mb-4 text-center">ĐĂNG NHẬP</p>

            <div class="form-outline mb-4">
                <label class="form-label h5" for="form1Example1" style="margin-left: 0px;">Tên đăng nhập</label>
                <input type="text" id="form1Example1" name="username" class="form-control" {{form.username}}

                <div class="form-notch">
                    <div class="form-notch-leading" style="width: 9px;"></div>
                    <div class="form-notch-middle" style="width: 88.8px;"></div>
                    <div class="form-notch-trailing"></div>
                </div>
                
            </div>

            <div class="form-outline mb-4">
                <label class="form-label h5" for="form1Example2" style="margin-left: 0px;">Mật khẩu</label>
                <input type="password" id="form1Example2" name="password" class="form-control" {{form.password}}

                <div class="form-notch">
                    <div class="form-notch-leading" style="width: 9px;"></div>
                    <div class="form-notch-middle" style="width: 64px;"></div>
                    <div class="form-notch-trailing"></div>
                </div>
                
            </div>
            {% if messages %}
                <p class="text-danger">{{ messages }}</p>
            {% endif %}
        
            <div  class="h5 mb-4 text-center">
                <p>Quên mật khẩu</p>
                <button type="submit" class="btn btn-dark k">Đăng nhập</button>
            </div>
            <div  class="h5 mb-4 text-center">
                <a href="{%url 'register' %}" type="button" class="btn btn-outline-dark ">Đăng ký</a>
            </div>
            
        </form>
    </section>
    <hr>
    
    <div class="container px-5">
        <div class="row">
            <p class="h2 mb-4 text-center">Đăng ký nhận thông tin mới từ <span class="h1 span-logo"> POVERIA</span></p>
        </div>

        <div class="form-outline mb-4" style="padding: 0 27%">
            <input type="email" id="form1Example1" class="input-footer" placeholder="Nhập email của bạn tại đây">

            <div class="form-notch">
                <div class="form-notch-leading" style="width: 9px;"></div>
                <div class="form-notch-middle" style="width: 88.8px;"></div>
                <div class="form-notch-trailing"></div>
            </div>
        </div>
        <div class="row text-center">
            <div class="py-2">
                <input type="checkbox" class="py-4"> <span>Tôi đồng ý với các chính sách và điều khoản</span><Br>
                <div style="padding: 1% 33% ">
                    <a href="{%url 'register' %}" type="button" class="btn btn-dark k">ĐĂNG KÝ</a>
                </div>
            </div>
            
            
        </div>
    </div>

    <div  style="background: #d9d9d9; padding-top: 2%">
        
        <div class="container">
            <div class="row text-center pl-3" style="text-align: justify">
                <div class="col-4">
                    <p  class="h1 span-logo">POVERIA</p>
                </div>
                <div class="col-4">
                    <p class="h5">DANH MỤC</p>
                </div>
                <div class="col-4">
                    <p class="h5">PHỤ KIỆN</p>
                </div>
            </div>

            <div  class="row text-center pl-3" style="text-align: justify">
                <div class="col-4">
                    <p class="content-ft">11A Quang Trung, Hà Đông, Hà Nội</p>
                </div>
                <div class="col-4">
                    <p class="content-ft">Áo</p>
                </div>
                <div class="col-4">
                    <p class="content-ft">Túi xách</p>
                </div>
            </div>

            <div class="row text-center pl-3">
                <div class="col-4">
                    <p class="content-ft">Số điện thoại: 0984xxxxxx</p>
                </div>
                <div class="col-4">
                    <p class="content-ft">Quần</p>
                </div>
                <div class="col-4">
                    <p class="content-ft">Thát lưng</p>
                </div>
            </div>

            <div class="row text-center p2-3 pb-5">
                <div class="col-4">
                    <p class="content-ft">Email: Poveria@gmail.com</p>
                </div>
                <div class="col-4">
                    <p class="content-ft">Váy</p>
                </div>
                <div class="col-4">
                    <p class="content-ft">Mũ</p>
                </div>
            </div>
            
        </div>
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts' %}"></script>
</body>

</html>

customers/templates/payment_method.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>User</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <!-- Google fonts-->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&amp;display=swap"
        rel="stylesheet" />
    <link
        href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&amp;display=swap"
        rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&amp;display=swap"
        rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>

<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm" id="mainNav">
        <div class="container px-5 d-flex">
            <a class="navbar-brand fw-bold" href="#page-top"> <img src="/static/assets/images/Lymn_logo.png" alt=""></a>

            <a class="nav-toggler d-block d-md-none text-dark" data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation" href="javascript:void(0)"><i class="bi-list bi-close"></i></a>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-lg-0">
                    <li class="nav-item"><a class="nav-link me-lg-3" href="{% url 'home' %}">TRANG CHỦ</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="quanao.html">QUẦN ÁO</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="phukien.html">ĐIỆN TỬ</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="phukien.html">SÁCH</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="blog.html">BLOG</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="lienhe.html">LIÊN HỆ</a></li>
                    <li class="nav-item"><a class="nav-link" href="gioithieu.html">GIỚI THIỆU</a></li>
                </ul>

            </div>
        </div>
    </nav>
    <!-- Mashead header-->
    <header class="masthead">
        <div class="container px-5">
            <div class="row m-0">
                <div class="col-6 d-flex " >
                    <span>Danh sách yêu thích (0) |</span>
                    <input class="form-input" type="search" placeholder="Tìm kiếm" aria-label="Tìm kiếm" />
                    <i class="bi-search"></i>
                </div>
                <div class="pb-4 col-6 content-header dropdown" style="padding-right: 0; text-align: right; width:51%">

                    <a href="{%url 'view_cart' %}"><span>Giỏ hàng ({{amount}})</span></a> | <i class="bi-person-fill"
                        aria-hidden="true"></i><span class="dropdown-toggle" data-bs-toggle="dropdown"> {{user.username}}
                        </i></span></span>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="Userdd">
                        <a class="dropdown-item" href="dangky.html"><i class="bi bi-person-circle m-r-5 m-l-5"></i>
                            Quản lý tài khoản</a>

                        <a class="dropdown-item" href="/"><i
                                class="bi bi-box-arrow-in-left m-r-5 m-l-5"></i> Đăng xuất</a>
                    </div>
                </div>

            </div>
            <div class="row m-0 bg-light">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item text-dark"><a class="home" href="trangchu.html">Trang chủ</a></li>
                    
                    <li class="breadcrumb-item text-dark" ><a class="home" href="/customers/view-cart/">Giỏ hàng</a></li>
                    <li class="breadcrumb-item text-dark"><a class="home" href="/customers/get-receiver/">Thông tin nhận hàng</a></li>
                    <li class="breadcrumb-item text-dark">Chọn phương thức thanh toán</li>
                </ul>
            </div>
        </div>
    </header>
    
    <section  style="padding: 0 10%; margin-top:3%">
        
        <div style="padding:0 5%; margin-top: 1%">
            <form method="POST" action="{% url 'payment' %}" class="form-login" style="width: 100%; margin: 3% 0; background: #EDEDED; border: none">
                {% csrf_token %}
                <p class="h4 mb-4 text-center">Thông tin thanh toán</p>
               
                <div class="form-outline mb-4" style="width: 48%;">
                    <label class="form-label h5" for="form1Example2" style="margin-left: 0px;">Phương thức thanh toán</span></label>
                    <select name="method" required="" id="id_method"
                    class=" form-control form-control-alternative" >
                    </option>
                    {% for k, v in methods %}
                        {% comment %} {%if k == %} {% endcomment %}
                        <option value="{{ k }}" >{{v}}</option>

                    {% endfor %}

                    </select>
                    <div class="form-notch">
                        <div class="form-notch-leading" style="width: 9px;"></div>
                        <div class="form-notch-middle" style="width: 64px;"></div>
                        <div class="form-notch-trailing"></div>
                    </div>
                </div>
                    
                <div  class="h5 mb-4 text-center" style="padding: 0 25%">
                    <button type="submit" class="btn btn-dark ">Xác nhận</button>
                </div>
                
            </form>

        <div>
        
    </section>
    <hr>
    
    <div class="container px-5">
        <div class="row">
            <p class="h2 mb-4 text-center">Đăng ký nhận thông tin mới từ <span class="h1 span-logo"> POVERIA</span></p>
        </div>

        <div class="form-outline mb-4" style="padding: 0 27%">
            <input type="email" id="form1Example1" class="input-footer" placeholder="Nhập email của bạn tại đây">

            <div class="form-notch">
                <div class="form-notch-leading" style="width: 9px;"></div>
                <div class="form-notch-middle" style="width: 88.8px;"></div>
                <div class="form-notch-trailing"></div>
            </div>
        </div>
        <div class="row text-center">
            <div class="py-2">
                <input type="checkbox" class="py-4"> <span>Tôi đồng ý với các chính sách và điều khoản</span><Br>
                <div style="padding: 1% 33% ">
                    <button type="button" class="btn btn-dark k">ĐĂNG KÝ</button>
                </div>
            </div>
            
            
        </div>
    </div>

    <div  style="background: #d9d9d9; padding-top: 2%">
        
        <div class="container">
            <div class="row text-center pl-3" style="text-align: justify">
                <div class="col-4">
                    <p  class="h1 span-logo">POVERIA</p>
                </div>
                <div class="col-4">
                    <p class="h5">DANH MỤC</p>
                </div>
                <div class="col-4">
                    <p class="h5">PHỤ KIỆN</p>
                </div>
            </div>

            <div  class="row text-center pl-3" style="text-align: justify">
                <div class="col-4">
                    <p class="content-ft">11A Quang Trung, Hà Đông, Hà Nội</p>
                </div>
                <div class="col-4">
                    <p class="content-ft">Áo</p>
                </div>
                <div class="col-4">
                    <p class="content-ft">Túi xách</p>
                </div>
            </div>

            <div class="row text-center pl-3">
                <div class="col-4">
                    <p class="content-ft">Số điện thoại: 0984xxxxxx</p>
                </div>
                <div class="col-4">
                    <p class="content-ft">Quần</p>
                </div>
                <div class="col-4">
                    <p class="content-ft">Thát lưng</p>
                </div>
            </div>

            <div class="row text-center p2-3 pb-5">
                <div class="col-4">
                    <p class="content-ft">Email: Poveria@gmail.com</p>
                </div>
                <div class="col-4">
                    <p class="content-ft">Váy</p>
                </div>
                <div class="col-4">
                    <p class="content-ft">Mũ</p>
                </div>
            </div>
            
        </div>
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts' %}"></script>
</body>

</html>